version: '3.8'
services:
  cache:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
  app:
    build: .
    depends_on:
      - cache
    ports:
    - 8080:8080
    volumes: 
      - cache:/data
    environment: 
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    links:
    - cache
volumes:
  cache:
    driver: local